name: "Publish"
on:
  pull_request:
jobs:
  emanote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: mxschmitt/action-tmate@v3